#  The function below ready the protocol of a single participant (as
#  generated by py-span-task) and calculates the working memory scores
#  discussed in Conway et al. (2005).

wm.scores <- function(filename, threshold=2/3) {

  d <- read.table(filename, header=TRUE)
  d <- d[d$phase=="test",,drop=F]

  accuracy <- sum(d$verification) / sum(d$level)
  message(paste("Overall accuracy in the processing task:",
                format(accuracy, digits=2)))

  pcu <- mean(d$memory / d$level)
  pcl <- sum(d$memory) / sum(d$level)
  anu <- sum(d$level == d$memory) / nrow(d) 
  anl <- sum(d$level * (d$level == d$memory)) / sum(d$level)

  thresh.func <- function(x) { mean(x==1)>threshold }
  t <- tapply(d$memory / d$level, d$level, thresh.func)
  wmc <- max(as.integer(c("0", names(t)[t])))

  t <- tapply(d$memory==d$level, d$level,
              function(x) { sum(x)/length(x)>threshold })
  wmc <- max(as.integer(c("0", names(t)[t])))

  list(wmc=wmc, pcu=pcu, anu=anu, pcl=pcl, anl=anl, accuracy=accuracy)
}

